build: off
environment:

  matrix:
    - PLATFORMIO_CI_SRC: "src/"

install:
    - cmd: git submodule update --init --recursive
    - cmd: SET PATH=%PATH%;C:\Python27\Scripts
    - cmd: pip install -U platformio

test_script:
    - cmd: cp src/config-example.h src/config.h
    - cmd: platformio run
